### ISSUE TITLE
How to use JSON RPC API? (need example)

### ISSUE THREAD

**Issue by DrMartiner** [btcsuite/btcd#1705]
Hi everyone,

I have turned up in docker-compose:
```yml
version: "2"
services:
  btcd:
    image: btcsuite/btcd:latest
    restart: unless-stopped
    volumes:
      - ./data/btcd/:/root/.btcd
    ports:
      - 8333:8333
      - 8334:8334
    command: ["--rpcuser=user", "--rpcpass=pass"]
```

Could someone show me example of curl's request to JSON RPC?

Currently this request have returned `curl: (56) Recv failure: Connection reset by peer`
```bash
curl --header "Content-Type: application/json" \
--request POST  \
--data '{"jsonrpc": "1.0" ,"method": "...","params": [...], "user": "user", "password": "pass"}' \
http://127.0.0.1:8333
``` 

What is wrong?

Best regards
