### ISSUE TITLE
Extremely high disk use

### ISSUE THREAD

**Issue by C0MM4ND** [btcsuite/btcd#1943]
Version: built docker container with commit e563459b72df634ca5731ac6c93e9ffbfd36dd93
Disk: HDD
Docker:
```
version: "3"

services:
  btcd:
    container_name: btcd
    hostname: btcd
    image: btcd:latest
    restart: unless-stopped
    volumes:
      - /mnt/hdd14t/btcd:/root/.btcd
    ports:
      - 18333:8333
      - 8334:8334
    command:
      - --txindex
      - --addrindex
      - --blocksonly
      - --rpclisten=:8334
      - --rpccert=/root/.btcd/rpc.cert
      - --rpckey=/root/.btcd/rpc.key
      - -u=btcd
      - -P=pass
```

Problem: always high disk write (>30MB
Realtime:
![image](https://user-images.githubusercontent.com/12538215/217214485-a5d03364-a2e4-4727-8b9a-6b714dac1723.png)

Accumulated:
![image](https://user-images.githubusercontent.com/12538215/217214742-fe93fef4-3510-40d7-a8db-5b570c1bbdcf.png)

This is abnormal, the writing rate and volumn is even more than an ethereum archive node.
